# This is the master database
development:
  adapter: mysql
  host: localhost
  database: octopus_replication_1
# Test database.
test:
  adapter: mysql
  host: localhost
  database: octopus_replication_test
