# This is the master database
development:
  adapter: mysql
  username: root
  password: 
  database: octopus_replication_1

# Test database.
test:
  adapter: mysql
  username: root
  password: 
  database: octopus_replication_test
